services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    ports:
      - 8080:8080
    environment:
      - Black_Kiwi_ENV=dev
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  public_postgis:
    container_name: public_postgis
    image: aleben/itlandfill-cas-postgis-preloaded:latest
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=black-kiwi_administrator
      - POSTGRES_PASSWORD=6whuUYTEhyA2ShR35
      - POSTGRES_DB=black-kiwi

volumes:
  postgres_data: 
  