version: '3'

services:
  postgis:
    container_name: postgis
    image: aleben/itlandfill-cas-postgis-preloaded:1.7
    restart: on-failure
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=black-kiwi_administrator
      - POSTGRES_PASSWORD=6whuUYTEhyA2ShR35
      - POSTGRES_DB=black-kiwi
  go_api:
    container_name: go_api
    image: aleben/itlandfill-cas-go_api:1.7
    restart: on-failure
    depends_on:
      - postgis
    ports:
      - 62950:8080
    networks:
      - default
      - backend
  public_postgis:
    container_name: public_postgis
    image: aleben/itlandfill-cas-postgis-preloaded:1.7
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - default
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=black-kiwi_administrator
      - POSTGRES_PASSWORD=6whuUYTEhyA2ShR35
      - POSTGRES_DB=black-kiwi
    profiles:
      - debug

networks:
  backend:
    name: black-kiwi-backend
    internal: true
  default:

volumes:
  postgres_data: 